name: Generate Snake (Dark + Light, synced final bar)

on:
  schedule:
    - cron: "0 0 * * *"  # Génération quotidienne
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: nik552
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=#FF0000
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#F3BA2F

      - name: Update final progress bar color for light mode
        run: |
          sed -i 's/fill:#000000/fill:#FF0000/g' dist/github-contribution-grid-snake.svg

      - name: Update final progress bar color for dark mode
        run: |
          sed -i 's/fill:#FFFFFF/fill:#F3BA2F/g' dist/github-contribution-grid-snake-dark.svg

      - name: Commit generated Snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/*.svg
          git commit -m "chore: update dark+light snake with synced final bar" || echo "No changes to commit"
          git push origin main
